## importazione librerie

In [23]:
import pandas as pd

## visualizzazione dataset

In [24]:
df = pd.read_csv("vehicles_dataset.csv")
df.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state
0,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,az
1,11900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ar
2,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fl
3,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ma
4,4900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nc

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         426880 non-null  int64
 1   year          425675 non-null  float64
 2   manufacturer  409234 non-null  str
 3   model         421603 non-null  str
 4   condition     252776 non-null  str
 5   cylinders     249202 non-null  str
 6   fuel          423867 non-null  str
 7   odometer      422480 non-null  float64
 8   title_status  418638 non-null  str
 9   transmission  424324 non-null  str
 10  drive         296313 non-null  str
 11  size          120519 non-null  str
 12  type          334022 non-null  str
 13  paint_color   296677 non-null  str
 14  state         426880 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 48.9 MB

 ## valori nulli 
 5   year          425675 non-null 
 6   manufacturer  409234 non-null 
 7   model         421603 non-null    
 8   condition     252776 non-null     
 9   cylinders     249202 non-null     
 10  fuel          423867 non-null      
 11  odometer      422480 non-null  
 12  title_status  418638 non-null      
 13  transmission  424324 non-null      
 15  drive         296313 non-null    
 16  size          120519 non-null  
 17  type          334022 non-null     
 18  paint_color   296677 non-null


## valori stringhe   
 6   manufacturer  409234 non-null  str    
 7   model         421603 non-null  str    
 8   condition     252776 non-null  str    
 9   cylinders     249202 non-null  str    
 10  fuel          423867 non-null  str    
 12  title_status  418638 non-null  str    
 13  transmission  424324 non-null  str    
 15  drive         296313 non-null  str    
 16  size          120519 non-null  str    
 17  type          334022 non-null  str    
 18  paint_color   296677 non-null  str    
 22  state         426880 non-null  str

In [32]:
# df["url"].unique()  

# df["region"].unique()  

#df["model"].unique()  

df["manufacturer"].unique()  

# df["condition"].unique()  

# df["cylinders"].unique()  

#df["fuel"].unique()  

# df["title_status"].unique()  

# df["transmission"].unique()  

#df["VIN"].unique()  

# df["drive"].unique()  

# df["size"].unique()  

# df["paint_color"].unique()  

# df["image_url"].unique()  

#df["description"].unique()  

# df["state"].unique()  

# df["posting_date"].unique()  

# df["odometer"].unique()

<StringArray>
[              nan,             'gmc',       'chevrolet',          'toyota',
            'ford',            'jeep',          'nissan',             'ram',
           'mazda',        'cadillac',           'honda',           'dodge',
           'lexus',          'jaguar',           'buick',        'chrysler',
           'volvo',            'audi',        'infiniti',         'lincoln',
      'alfa-romeo',          'subaru',           'acura',         'hyundai',
   'mercedes-benz',             'bmw',      'mitsubishi',      'volkswagen',
         'porsche',             'kia',           'rover',         'ferrari',
            'mini',         'pontiac',            'fiat',           'tesla',
          'saturn',         'mercury', 'harley-davidson',          'datsun',
    'aston-martin',      'land rover',          'morgan']
Length: 43, dtype: str

In [26]:
df.describe()

              price           year      odometer
count  4.268800e+05  425675.000000  4.224800e+05
mean   7.519903e+04    2011.235191  9.804333e+04
std    1.218228e+07       9.452120  2.138815e+05
min    0.000000e+00    1900.000000  0.000000e+00
25%    5.900000e+03    2008.000000  3.770400e+04
50%    1.395000e+04    2013.000000  8.554800e+04
75%    2.648575e+04    2017.000000  1.335425e+05
max    3.736929e+09    2022.000000  1.000000e+07

## Per evitare leakage prima di fare qualsiasi cosa divido in train e test

In [28]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['price'])
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## pulizia dataset 
rimozione colonne inutili

rimozione valori nulli

In [ ]:
# valori nulli 426880tot 

#  5   year          425675 non-null  float64 ✔
#  6   manufacturer  409234 non-null str
#  7   model         421603 non-null  str  ✔
#  8   condition     252776 non-null   str  
#  9   cylinders     249202 non-null   str  
#  10  fuel          423867 non-null  str   ✔ 
#  11  odometer      422480 non-null  float64
#  12  title_status  418638 non-null  str    
#  13  transmission  424324 non-null str ✔    
#  15  drive         296313 non-null str   
#  16  size          120519 non-null str 
#  17  type          334022 non-null  str   
#  18  paint_color   296677 non-null  str

# essendo pochi i valori nulli in fuel possiamo cancellare tute le righe nulle 
X_train = X_train.dropna(subset=['fuel'])
y_train = y_train.loc[X_train.index] 

X_test = X_test.dropna(subset=['fuel'])
y_test = y_test.loc[X_test.index]

# 2. Verifica finale definitiva
print(f"Nulli residui in X_train: {X_train['fuel'].isnull().sum()}")
print(f"Nulli residui in X_test: {X_test['fuel'].isnull().sum()}")
print(f"Dimensioni finali X_train: {X_train.shape}")
print(f"Dimensioni finali X_test: {X_test.shape}")

#year 
X_train = X_train.dropna(subset=['year'])
y_train = y_train.loc[X_train.index] 

X_test = X_test.dropna(subset=['year'])
y_test = y_test.loc[X_test.index]

#model
X_train = X_train.dropna(subset=['model'])
y_train = y_train.loc[X_train.index] 

X_test = X_test.dropna(subset=['model'])
y_test = y_test.loc[X_test.index]

#transmission
X_train = X_train.dropna(subset=['transmission'])
y_train = y_train.loc[X_train.index] 

X_test = X_test.dropna(subset=['transmission'])
y_test = y_test.loc[X_test.index]

Nulli residui in X_train: 0
Nulli residui in X_test: 0
Dimensioni finali X_train: (339129, 14)
Dimensioni finali X_test: (84738, 14)